server:
  port: 20851
#网关
spring:
  gateway:
    tokenUri: 192.168.12.49:8090/zhsj/base/api
  application:
    name: community-old_activity-service
#配置reis
  redis:
    database: 0
    host: 192.168.12.49
    password: text_profile
    port: 6379
    timeout: 7000
    jedis:
      pool:
        max-idle: 10000
        min-idle: 10
        max-active: -1
        max-wait: -1
#数据库
  datasource:
    druid:
      username: root
      password: dev_zhsj_mysql
      url: jdbc:mysql://192.168.12.49/zhsj_community_yanglao_yiliao?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
#mybatisplus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0
#配置eureka注册
eureka:
  client:
    service-url:
      defaultZone: http://192.168.12.49:36366/eureka
  instance:
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}







